project_name: ebs-autoscale
gitlab_urls:
  api: '{{ .Env.CI_API_V4_URL }}'
  download: '{{ .Env.CI_SERVER_URL }}'
  use_package_registry: true
  use_job_token: true
release:
  gitlab:
    name: '{{ .Env.CI_PROJECT_ID }}'
  mode: append
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
      - arm64
nfpms:
  - maintainer: Jon Hinton
    description: Manages an auto-scaling ebs volume array
    homepage: https://github.com/jhinton/ebs-autoscale
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin
    contents:
      - src: service/systemd/ebs-autoscale-monitor.service
        dst: /usr/lib/systemd/system/ebs-autoscale-monitor.service
      - src: service/ebs-autoscale.json
        dst: /etc/ebs-autoscale/ebs-autoscale.json

    overrides:
      rpm:
        dependencies:
          - btrfs-progs
      deb:
        dependencies:
          - btrfs-progs
    scripts:
      postinstall: service/systemd/install.sh
      postremove: service/systemd/uninstall.sh

