name: Go CI/CD

on:
  push:
    branches:
      - '**'  # The workflow runs on every push to any branch
  pull_request:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  extract-go-version:
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.extract.outputs.go_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Go version from go.mod
        id: extract
        run: |
          VERSION=$(grep '^go ' go.mod | awk '{print $2}')
          echo "go_version=${VERSION}" >> $GITHUB_ENV
          echo "::set-output name=go_version::${VERSION}"

  lint:
    runs-on: ubuntu-latest
    needs: extract-go-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.extract-go-version.outputs.go_version }}

      - name: Determine golangci-lint version
        id: linter_version
        run: |
          case "${{ needs.extract-go-version.outputs.go_version }}" in
            "1.20") LINTER_VERSION="v1.52" ;;
            "1.21") LINTER_VERSION="v1.54" ;;
            "1.22") LINTER_VERSION="v1.55" ;;
            "1.23") LINTER_VERSION="v1.61" ;;
            *) echo "Unsupported Go version: ${{ needs.extract-go-version.outputs.go_version }}"; exit 1 ;;
          esac
          echo "LINTER_VERSION=$LINTER_VERSION" >> $GITHUB_ENV
          echo "::set-output name=linter_version::$LINTER_VERSION"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.LINTER_VERSION }}
          args: --timeout 5m ./ebs_autoscale/

  test:
    runs-on: ubuntu-latest
    needs: extract-go-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.extract-go-version.outputs.go_version }}

      - name: Install go-junit-report
        run: |
          go install github.com/jstemmer/go-junit-report@latest

      - name: Run tests and generate JUnit report
        run: |
          go test -v ./ebs_autoscale/... | go-junit-report > result.xml

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: result.xml

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.extract-go-version.outputs.go_version }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
